apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://3.109.216.63/api"
  NEXTAUTH_URL: "http://3.109.216.63"
  NEXTAUTH_SECRET: PCQE+xteOPGbuXdJtSyS69PPuph3l6P+wtF3cGnxJnA=
  JWT_SECRET: fa446b124b979acb19196dd23337e7991be206f0fb381c53fa29bf87a1c92f9b
