apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
        - name: migration
          image: dhruvjaindocker/k8s-shop-app:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "echo 'Migration completed successfully' && exit 0"]
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/easyshop"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: OnFailure
      activeDeadlineSeconds: 300
