apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
        - name: migration
          image: dhruvjaindocker/k8s-shop-migration:latest
          imagePullPolicy: Always
          command: ["npx"]
          args: ["ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: easyshop-config
                  key: MONGODB_URI
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: OnFailure
      activeDeadlineSeconds: 600  # Increased to 10 minutes
  backoffLimit: 3  # Allow 3 retries
  ttlSecondsAfterFinished: 300  # Clean up job after 5 minutes
