apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
        - name: migration
          image: dhruvjaindocker/k8s-shop-migration:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
