apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  backoffLimit: 1                # retry only once if fails
  template:
    spec:
      containers:
        - name: migration
          image: dhruvjaindocker/k8s-shop-migration:latest   # <-- use correct migration image if available
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["echo 'Migration completed successfully' && exit 0"]
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/easyshop"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: Never        # best practice for jobs
